---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: product-deployment
spec:
  selector:
    matchLabels:
      app: product
  replicas: 2
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: product:v1
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: product
  namespace: default
spec:
  selector:
    app: product
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: NodePort